language: go
sudo: false
go:
         - 1.6
         - 1.7
         - tip

install:
  - go get -v github.com/codegangsta/cli
script:
    - make test
    - make build

matrix:
    allow_failures:
        - go: tip
