language: go
sudo: false
go:
         - "1.8"
         - "1.9"
         - "1.10"
         - tip

install:
  - go get -v github.com/codegangsta/cli
  - go get -u github.com/nlopes/slack
  - go get github.com/tbruyelle/hipchat-go/hipchat
  - go get github.com/deckarep/gosx-notifier
script:
    - go test -v -cover ./...
    - make build

matrix:
    allow_failures:
        - go: tip
        - go: "1.10"
